### ISSUE TITLE
Can you explain the use case of this derequire module

### ISSUE THREAD

**Issue by rande** [calvinmetcalf/derequire#25]
Let's say we don't have a good js knowledge ;)

Thanks

**Comment by calvinmetcalf** [comment]
see #22 but basically when browserify or another bundler bundles a modules it looks like 

```js
var bar = require('bar');
function (require, export, module){
    var foo = require('foo');
}
```

other modules loaders do not always handle this well and try to load 'foo', s this will turn it into

```js
var bar = require('bar');
function (__dereq, export, module){
    var foo = __dereq('foo');
}
```

only changing the require that is bound to something else in it's scope.
