### ISSUE TITLE
Create LICENSE file

### ISSUE THREAD

**Issue by jaredsmith** [calvinmetcalf/derequire#31]
Could you please create a LICENSE file with your copyright information and the text of the MIT license?  The MIT license requires that the text of the license accompany the source code.

**Comment by zertosh** [comment]
It's convention to use the license field in the [package.json](https://github.com/hughsk/envify/blob/c42c2052e33f82b651a992686c3578639bf0339b/package.json#L17) (see https://docs.npmjs.com/files/package.json#license). Only including an actual license file if the license doesn't have a SPDX identifier.

**Comment by jaredsmith** [comment]
It may be convention, but it's also going against the MIT license itself.  The MIT license specifically states "The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software."  Some other licenses are more lenient in this regard, but the MIT license in particular spells it out quite clearly.
