### ISSUE TITLE
Exclude external dependencies

### ISSUE THREAD

**Issue by falsandtru** [calvinmetcalf/derequire#35]
Some `require` function calling which calls external libraries are desired to keep that function name because we cannot **rebundle** derequired libraries using browserify. Could you add the exclude option for rebundling?

```js
derequire(code, [
  {
    exclude: ['another'], // `require('another')` -> `require('another')`
    from: 'require',  // `require('./index.js')` -> `_dereq_('./index.js')`
    to: '_dereq_'
  }
]);
```

**Comment by calvinmetcalf** [comment]
Derequire should not ever change how the code functions, like a minifier it only changes local variables named require, in other words unless you are doing something like statically searching for require calls derequire isn't going to be a problem. 

Do you have an actual example of the problem you are having?

**Comment by falsandtru** [comment]
Thanks for the answer. An actual example is https://github.com/falsandtru/pjax-api/issues/23. I tried to rebundle my derequired libraries (it is different now), but I could not that. I think if derequire works only for internal dependency resolving, I could do it.

**Comment by calvinmetcalf** [comment]
looking at the issue I'm pretty sure derequire is not the problem, the way derequire works is as follows, say you have the code

```js
var foo = require('bar');
function bar(require) {
   return require('baz');
}
function baz() {
   var require = function (){}
   return require('baz');
}
console.log('require');
```

it would turn it into 

```js
var foo = require('bar');
function bar(__dereq__) {
   return __dereq__('baz');
}
function baz() {
   var __dereq__ = function (){}
   return __dereq__('baz');
}
console.log('require');
```
so in other words if you have any requires that are defined  by external scripts they will not be effected by derequire

as for what you are doing, I don't understand why you are not including your own dependencies in the package.json and/or your own bundle, at the very least the include them in the bundle pointed to by your main.js in the package.json so if people require your library they don't have to resort to any hacks to include

**Comment by falsandtru** [comment]
Certainly, and I found a case that cannot resolve external dependencies using `require` instead of `__dereq__`. This is not a derequire's problem. Thanks for instructing!
