### ISSUE TITLE
Exclude modules from derequire?

### ISSUE THREAD

**Issue by JakeSidSmith** [calvinmetcalf/derequire#36]
Hello, @calvinmetcalf 

So, upon trying to bundle a React library recently using browserify & derequire, I ran into a problem.

If I bundle React with the module then when it's installed you end up with 2 versions of React running in your application, which causes a host of problems. Alternatively you can exclude modules from your bundle, but then after derequiring, the libraries will not get required when building your application.

My suggestion is that another option is added (with the same syntax as browserify's CLI) so that certain requires can be excluded from derequiring e.g.

```shell
browserify --exclude react input.js | derequire --exclude react > output.js
```

Note: browserify's exclude is also aliased to `-u`. https://github.com/substack/node-browserify#usage

This the above command would not bundle React with the library, but would also not rename the requires. So the following:

```javascript
var React = require('react');
var otherLib = require('other-lib');
```

Would compile to:

```javascript
var React = require('react');
var otherLib = _dereq_('other-lib');
```

I started having a play around with this here: https://github.com/JakeSidSmith/derequire/pull/1

I'm not certain that this approach will even solve my problem, but haven't got it to a suitable point to test it yet.

I'm using a custom walker for the AST, and having not worked with escope before was a little confused by all the scope stuff. Currently all tests are passing (plus my new addition) except for a couple of the larger ones, in which certain requires are not supposed to be replaced. I believe this is because they are "tainted"? Though I'm not sure of the meaning.

Let me know what your thoughts are, and if you could explain what "tainted" is, or why those couple of tests have some requires that are not modified, that'd be really helpful. :)

**Comment by JakeSidSmith** [comment]
After some digging around, I think I have a better understanding of escope. Will update my branch when I have a sec.

**Comment by calvinmetcalf** [comment]
Why do you even need derequire, it's primarily intended for libraries not
apps

**Comment by calvinmetcalf** [comment]
Oh I see it's a library, but why do you even need to bundle it?

**Comment by JakeSidSmith** [comment]
Well, this basically all started because we are using a third party library in one of our apps, and they were using ES6 / JSX syntax, which we were not using (and wouldn't want to parse node modules anyway). We forked their lib to make some changes, but due to the bundling, derequire, etc, hit the issue of either having 2 versions of React or no React for the lib.

Tried fixing this by simply using babel to parse their lib on publish, but we just ran into even more issues (the library and app are both rather old and still run only in node 0.10).

Figured I'd have a go at modifying derequire as I thought it'd be a simple(ish) solution, and also because I'd probably learn a thing or two along the way.

Maybe this is a stupid idea. Figured it didn't hurt to see what you thought anyway. :)

**Comment by calvinmetcalf** [comment]
Well I don't know if it's a good idea or not, just trying to figure out the
big picture of the problem to see if the best solution is to modify this or
possibly change your build process (i.e. Using this as a wrench to hammer a
nail)

**Comment by JakeSidSmith** [comment]
Yeah, I'm unsure too. But I have a feeling that the need to bundle a lib without a couple of dependencies may be sensible for some cases, I'm just not sure if this is one of those.

**Comment by calvinmetcalf** [comment]
My main concern is that the point of derequire is that it doesn't affect how the lib works but this change would as it would selectively cause certain requires to point to global scope instead of local scope. 

So my first thought was maybe there is another way to set up your build process, is that lib open source? 

Next thought is your use case may have a bit of a maintenance burden so we may want to just make it a fork instead of including it in this lib

**Comment by JakeSidSmith** [comment]
It's a fork of `react-datepicker`. I believe the newest version has all the features we needed, but only supports React 0.14+ and we didn't want to upgrade our project from 0.13 for the sake of one library.

I believe the `externals` field in their webpack config excludes libs from their bundle.

https://github.com/Hacker0x01/react-datepicker/blob/master/webpack.config.js

We had wanted to move to using browserify for our fork of this lib, as we use that as our standard bundler for all projects, we'd had trouble getting their webpack build to run on postinstall, and consistency in your tools makes things easier to maintain.

At the moment we're just compiling the lib & then commiting it to the repo, which is less than ideal, but perhaps is better than spending all this time trying to get it to build itself on install.

**Comment by calvinmetcalf** [comment]
if you are requiring it from browserify then there isn't really any need to
pre bundle it, just add the babelify transform with the correct
configuration to the browserify member of your package.json (and include it
in the dependencies) then in your lib list react as an optional dependency

**Comment by JakeSidSmith** [comment]
So, I'd end up bundling my app with browserify, and browserfiy would use babelify on the library in question when required (as this would be defined inside that module)? But would not babelify my app? Or would I have to run babelify on my app also? I'd rather avoid babelifying my app as it's currently using reactify (which we really should swap out for babelify), but would likely be a lot of work.

**Comment by calvinmetcalf** [comment]
Right it would babelify just the library not the whole app

**Comment by JakeSidSmith** [comment]
Ok, cool. I'll give that a go. I'm sure even if that doesn't solve my issue, there must be a better way. Feel free to close this issue. I'll give you a shout if I come up with a more suitable reason to exclude modules from derequire. :)
