### ISSUE TITLE
escope dependency is out of date

### ISSUE THREAD

**Issue by jhogendorn** [calvinmetcalf/derequire#37]
Hey there,

I'm currently using gulp-derequire@latest on node 6.9.1, npm 3.10.9. The latest version of derequire is using a very old version of escope, which means you get this error:

```
node_modules/estraverse/estraverse.js:517
                        throw new Error('Unknown node type ' + nodeType + '.');
                        ^

Error: Unknown node type AssignmentPattern.
```

When you use derequire. This appears to be a solved issue in the underlying libraries, with estraverse >4.2.0 being the minimum version for the fix.

Is there any chance of this being updated to resolve this bug down the bottom of the dependency chain?

**Comment by calvinmetcalf** [comment]
I'm assuming this is caused by some es6 syntax, you wouldn't happen to know what it is so I can write a test

**Comment by jhogendorn** [comment]
Your point about es6 syntax gave me a prod to go bisecting my code to see where it was unhappy (I had interpreted this as a pure dependency issue), and after a few minutes found myself using `function(foo, bar = null)` in a library thats meant to be es5 etc. Thats what you get for swapping between projects I guess.

So this is less of an issue now, although I'd say the upgrade may still be worthwhile if theres no BC issues. Hope that helps with your test case!

**Comment by calvinmetcalf** [comment]
glad you figured it out, but yeah I'm going to add some tests that hit es6 syntax to make sure they work
