### ISSUE TITLE
Support ES2018 or later

### ISSUE THREAD

**Issue by falsandtru** [calvinmetcalf/derequire#42]
Looks like doesn't work since ES2017. Can support the latest syntax?

**Comment by falsandtru** [comment]
@calvinmetcalf Can you update?

**Comment by calvinmetcalf** [comment]
do you have an example of syntax that fails

**Comment by falsandtru** [comment]
derequire silently fails when input code has the `**` operator or the other new syntax (So I can't even know that derequire has failed from the result on terminal).

**Comment by calvinmetcalf** [comment]
v2.1.0

**Comment by falsandtru** [comment]
Thanks!
